### ISSUE TITLE
Separate README.md

### ISSUE THREAD

**Issue by okstaticzero** [theoy/npm-git-publish#25]
Is there a way to push a different README.md file to the published repo?

**Comment by theoy** [comment]
Hi @zerostatic -- the default design is to be compatible with `npm publish` mechanisms. I think for the scenario you're defining, you can set up a [standard `npm prepublishOnly` hook](https://docs.npmjs.com/misc/scripts#prepublish-and-prepare) to take a rename or copy a custom file from your codebase into the `README.md` path right before the contents get captured for publication. You can also use the [standard `.npmignore` feature](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) to prevent the original path/copy of your public README from being included in the published package.

Using this technique will also keep your automation compatible should you need to change your requirements, and decide to publish to a standard npm repository (either the public one, or a paid private version of the official npm repository).

Hope that's clear -- let me know if you want further clarification/examples 😄

**Comment by okstaticzero** [comment]
@theoy That makes sense. Thanks so much for the tips!
